'use strict';

const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');

function getPriorityColor(priority) {
  if (priority === 'HIGH') return '#27AE60';
  if (priority === 'MEDIUM') return '#E67E22';
  return '#95A5A6';
}

function getScoreColor(score) {
  if (score >= 8) return '#27AE60';
  if (score >= 6) return '#E67E22';
  return '#E74C3C';
}

function renderJobCard(job) {
  const borderColor = getPriorityColor(job.apply_priority);
  const scoreColor = getScoreColor(job.match_score);
  const applyUrl = job.applyUrl || '#';

  const reasons = Array.isArray(job.match_reasons) ? job.match_reasons : [];
  const bullet1 = reasons[0] ? `<li style="margin-bottom:4px">${reasons[0]}</li>` : '';
  const bullet2 = reasons[1] ? `<li style="margin-bottom:4px">${reasons[1]}</li>` : '';
  const reasonsHtml = (bullet1 || bullet2)
    ? `<ul style="margin:6px 0 6px 16px;padding:0;font-size:13px;color:#333">${bullet1}${bullet2}</ul>`
    : '';

  const tipHtml = job.tailoring_tip
    ? `<p style="margin:6px 0 0;font-style:italic;font-size:12px;color:#666">Tip: ${job.tailoring_tip}</p>`
    : '';

  return `
    <div style="border-left:5px solid ${borderColor};background:#F9F9F9;padding:12px 16px;margin-bottom:12px;border-radius:4px">
      <p style="margin:0 0 4px;font-size:15px;font-weight:bold;color:#1F4E79">${job.title || ''}</p>
      <p style="margin:0 0 6px;font-size:13px;color:#555">${job.company || ''} &mdash; ${job.location || ''}</p>
      <span style="display:inline-block;background:#E8F4FD;color:#1A5276;padding:2px 8px;border-radius:10px;font-size:11px;margin-bottom:6px">${job.source || ''}</span>
      <p style="margin:6px 0;font-size:13px"><strong style="color:${scoreColor}">AI Match: ${job.match_score !== undefined ? job.match_score : '?'}/10</strong></p>
      ${reasonsHtml}
      ${tipHtml}
      <a href="${applyUrl}" style="display:inline-block;background:#1F4E79;color:white;padding:6px 16px;border-radius:4px;text-decoration:none;font-size:13px;margin-top:8px">Apply Now</a>
    </div>`;
}

function renderSection(emoji, label, jobs) {
  if (!jobs.length) return '';
  const cards = jobs.map(renderJobCard).join('');
  return `
    <h2 style="font-size:16px;font-weight:bold;color:#1F4E79;border-bottom:2px solid #1F4E79;padding-bottom:6px;margin-top:24px;margin-bottom:12px">${emoji} ${label}</h2>
    ${cards}`;
}

function generateHTMLReport(jobsArray, dateString) {
  const total = jobsArray.length;
  const highCount = jobsArray.filter(j => j.apply_priority === 'HIGH').length;

  const highJobs = jobsArray.filter(j => j.apply_priority === 'HIGH');
  const medJobs = jobsArray.filter(j => j.apply_priority === 'MEDIUM');
  const lowJobs = jobsArray.filter(j => j.apply_priority === 'LOW');

  const body = total === 0
    ? `<p style="font-size:15px;color:#555;margin:32px 0">No new matching jobs found today. The agent will check again tomorrow.</p>`
    : renderSection('🔴', 'HIGH PRIORITY', highJobs) +
      renderSection('🟡', 'MEDIUM PRIORITY', medJobs) +
      renderSection('🟢', 'LOW PRIORITY', lowJobs);

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GCC Job Report</title></head>
<body style="margin:0;padding:0;background:#EBEBEB;font-family:Arial,Helvetica,sans-serif">
  <div style="max-width:680px;margin:0 auto;background:#ffffff">

    <!-- HEADER -->
    <div style="background:#1F4E79;padding:28px 32px">
      <h1 style="margin:0 0 8px;font-size:22px;color:#ffffff;font-weight:bold">GCC Job Opportunities &mdash; Daily Report</h1>
      <p style="margin:0 0 4px;font-size:14px;color:#ffffff">${dateString}</p>
      <p style="margin:0;font-size:14px;color:#ffffff">${total} new jobs found | ${highCount} High Priority</p>
    </div>

    <!-- CONTENT -->
    <div style="padding:16px 32px 24px">
      ${body}
    </div>

    <!-- FOOTER -->
    <div style="background:#F2F2F2;padding:16px 32px;text-align:center">
      <p style="margin:0 0 4px;font-size:12px;color:#888">Report generated by GCC Job Agent</p>
      <p style="margin:0;font-size:12px;color:#888">Next report scheduled: Tomorrow at 8:00 AM Gulf Time</p>
    </div>

  </div>
</body>
</html>`;
}

async function sendJobReport(jobsArray, dateString) {
  try {
    const html = generateHTMLReport(jobsArray, dateString);

    const reportPath = path.join(__dirname, '..', 'data', 'report-' + dateString + '.html');
    fs.writeFileSync(reportPath, html, 'utf8');

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: false,
      auth: {
        user: process.env.EMAIL_FROM,
        pass: process.env.EMAIL_PASSWORD,
      },
    });

    await transporter.sendMail({
      from: process.env.EMAIL_FROM,
      to: process.env.EMAIL_TO,
      subject: 'GCC Jobs - ' + jobsArray.length + ' New Matches - ' + dateString,
      html,
    });

    console.log('Email sent successfully to ' + process.env.EMAIL_TO);
    return { success: true };
  } catch (error) {
    console.error('Failed to send email report:', error);
    return { success: false, error: error.message };
  }
}

module.exports = { generateHTMLReport, sendJobReport };
